"""update

Revision ID: d9977c3e31d6
Revises: 0ed6480f3fe7
Create Date: 2025-09-25 11:40:36.305355

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d9977c3e31d6"
down_revision: str | Sequence[str] | None = "0ed6480f3fe7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
